---
# defaults file for docker
docker_pkg_deps:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

docker_pkg:
  - docker-ce
  - docker-ce-cli
  - containerd.io

docker_gpg_key: https://download.docker.com/linux/ubuntu/gpg
docker_repo_url: deb https://download.docker.com/linux/ubuntu bionic stable